from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.amazon.aws.hooks.s3 import S3Hook
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from datetime import datetime
from airflow.operators.bash import BashOperator
import os

JOB_LOCAL_DIR = "/opt/spark/jobs"
JOB_LOCAL_PATH = f"{JOB_LOCAL_DIR}/job1.py"
S3_BUCKET = "spark-jobs"
S3_KEYS = ["job1.py","job2.py"]


def fetch_spark_job():
    os.makedirs(JOB_LOCAL_DIR, exist_ok=True)
    hook = S3Hook(aws_conn_id="minio_s3")
    for key in S3_KEYS:
        hook.download_file(
            key=key,
            use_autogenerated_subdir=False,
            bucket_name=S3_BUCKET,
            local_path=JOB_LOCAL_DIR,
        preserve_file_name=True,
    )


with DAG(
    dag_id="pipeline_fetch-_sp_operator",
    start_date=datetime(2024, 1, 1),
    schedule_interval=None,
    catchup=False,
    tags=["spark", "minio","fetch","fetch_all_jobs","working","bash_operator_delete"],
) as dag:
    
    fetch_job = PythonOperator(
        task_id="fetch_spark_jobs_from_s3",
        python_callable=fetch_spark_job,
    )

    spark_submit = SparkSubmitOperator(
        task_id="run_spark_job",
        application=JOB_LOCAL_PATH,
        conn_id="spark_standalone",
        deploy_mode="client",
        name="airflow-spark-job",
        verbose=False,
        spark_binary="/opt/spark/bin/spark-submit",
    )

    delete_job_first = BashOperator(
        task_id="delete_spark_job_local_file_first",
        bash_command="rm -f /opt/spark/jobs/job1.py",        
    )

    delete_job = BashOperator(
        task_id="delete_spark_job_local_file",
        bash_command="rm -f /opt/spark/jobs/job1.py",        
    )

    delete_job_first >> fetch_job >> spark_submit >> delete_job
