from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.amazon.aws.hooks.s3 import S3Hook
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from datetime import datetime
from airflow.operators.bash import BashOperator
import boto3
from airflow.sensors.python import PythonSensor
import os

JOB_LOCAL_DIR = "/opt/spark/jobs"
JOB_LOCAL_PATH = [f"{JOB_LOCAL_DIR}/app_read_join.py", f"{JOB_LOCAL_DIR}/1_csv_write.py"]
S3_BUCKET = "spark-jobs"
S3_KEYS = ["app_read_join.py","1_csv_write.py"]


def fetch_spark_job():
    os.makedirs(JOB_LOCAL_DIR, exist_ok=True)
    hook = S3Hook(aws_conn_id="minio_s3")
    for key in S3_KEYS:
        hook.download_file(
            key=key,
            use_autogenerated_subdir=False,
            bucket_name=S3_BUCKET,
            local_path=JOB_LOCAL_DIR,
        preserve_file_name=True,
    )
def parquet_exists():
    s3 = boto3.client(
        "s3",
        endpoint_url="http://minio:9000",
        aws_access_key_id="mycustomuser",
        aws_secret_access_key="pakekfoeo3030d3*(&&&(*!",
    )

    response = s3.list_objects_v2(
        Bucket="analytics",
        Prefix="joined_orders/"
    )

    if "Contents" not in response:
        return False

    return any(obj["Key"].endswith(".parquet") for obj in response["Contents"])




with DAG(
    dag_id="pipeline_fetch-_sp_operator",
    start_date=datetime(2024, 1, 1),
    schedule_interval=None,
    catchup=False,
    tags=["spark", "minio","fetch","fetch_all_jobs","working","bash_operator_delete"],
) as dag:
    
    fetch_job = PythonOperator(
        task_id="fetch_spark_jobs_from_s3",
        python_callable=fetch_spark_job,
    )

    spark_submit_1 = SparkSubmitOperator(
        task_id="run_spark_job_1",
        application=JOB_LOCAL_PATH[0],
        conn_id="spark_standalone",
        deploy_mode="client",
        name="airflow-spark-job-1",
        verbose=False,
        spark_binary="/opt/spark/bin/spark-submit",
    )
    spark_submit_2 = SparkSubmitOperator(
        task_id="run_spark_job_2",
        application=JOB_LOCAL_PATH[1],
        conn_id="spark_standalone",
        deploy_mode="client",
        name="airflow-spark-job-2",
        verbose=False,
        spark_binary="/opt/spark/bin/spark-submit",
    )
    wait_for_parquet = PythonSensor(
    task_id="wait_for_parquet_files",
    python_callable=parquet_exists,
    poke_interval=10,
    timeout=300,
    mode="reschedule",
        )
    

    delete_job_first = BashOperator(
        task_id="delete_spark_job_local_file_first",
        bash_command="rm -f /opt/spark/jobs/app_read_join.py /" \
        "opt/spark/jobs/1_csv_write.py",        
    )

    delete_job_after = BashOperator(
        task_id="delete_spark_job_local_file",
        bash_command="rm -f /opt/spark/jobs/app_read_join.py /" \
        "opt/spark/jobs/1_csv_write.py",        
    )
    delete_job_first
    #delete_job_first >> fetch_job >> spark_submit_1 >> wait_for_parquet >> spark_submit_2 >> delete_job_after
